### PR TITLE
Update libbpf submodule to v1.0

### PR DESCRIPTION
**Pull request by tohojo**
Update the libbpf submodule, and update the code to remove all usage of
deprecated libbpf APIs.

Compile tested only...

### CODE REVIEW

**Comment by tohojo** [comment]
Cc @interduo

**Comment by interduo** [comment]
This was that. No warnings with new lib. Could You merge that with master?

**Comment by tohojo** [comment]
Yup, will do. Also Cc @thebracket FYI

**Comment by interduo** [comment]
@tohojo tried to compile xdp-cpumap-tc with libbpf from master branch.

```
In file included from /usr/include/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:83: xdp_pass_kern.o] Error 1
```

Do I need any special package in ubuntu for that?

**Comment by interduo** [comment]
Ok - there is a need to install **gcc-multilib** package for ubuntu

**Comment by interduo** [comment]
@tohojo only this error `./xdp-cpumap-tc/bin/xps_setup.sh: line 103: echo: write error: No such file or directory` I made an issue here: https://github.com/xdp-project/xdp-cpumap-tc/issues/12

**Pull request merged**
